---
- name: Create pve vm pool
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ pve_cluster_url }}/api2/json/pools"
    method: POST
    body_format: form-urlencoded
    body:
      poolid: "{{ item.name }}"
    status_code: [200,500]
    headers:
      Cookie: "PVEAuthCookie={{ pve_api_ticket.json.data.ticket }}"
      CSRFPreventionToken: "{{ pve_api_ticket.json.data.CSRFPreventionToken }}"
