---
- name: Get proxmox ticket for authentication
  ansible.builtin.uri:
    validate_certs: false
    url: "{{ pve_cluster_url }}/api2/json/access/ticket"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ pve_api_user }}"
      password: "{{ pve_api_password }}"
    status_code: 200
  register: pve_api_ticket

- name: Create VM pool/folder
  ansible.builtin.include_tasks: create-pool.yaml
  when: pve_pools is defined
  with_items:
    - "{{ pve_pools }}"

- name: Execute vm operation
  ansible.builtin.include_tasks: execute-vm-operation.yaml
  with_items:
    - "{{ pve_bulk_delete_vms | default([]) }}"
    - "{{ pve_bulk_rename_vms | default([]) }}"

- name: Send webhook
  ansible.builtin.include_tasks: send-webhook.yaml
  when: send_webhook|bool
