---
- name: Get proxmox ticket for authentication
  ansible.builtin.include_tasks: ticket.yaml

- name: Create VM pool/folder
  ansible.builtin.include_tasks: create-pool.yaml
  when: pve_pools is defined
  with_items:
    - "{{ pve_pools }}"

- name: Delete template/vm
  ansible.builtin.include_tasks: delete-vm.yaml
  when: pve_delete_vms is defined
  with_items:
    - "{{ pve_delete_vms }}"

- name: Rename template/vm
  ansible.builtin.include_tasks: rename-vm.yaml
  when: pve_rename_vms is defined
  with_items:
    - "{{ pve_rename_vms }}"
