---
- name: Get proxmox ticket for authentication
  ansible.builtin.include_tasks: ticket.yaml

- name: Create VM pool/folder
  ansible.builtin.include_tasks: create-pool.yaml
  when: pve_pools is defined
  with_items:
    - "{{ pve_pools }}"

- name: Bulk delete template/vm
  ansible.builtin.include_tasks: bulk-delete-vm.yaml
  when: pve_bulk_delete_vms is defined
  with_items:
    - "{{ pve_bulk_delete_vms }}"

- name: Single delete template/vm
  ansible.builtin.include_tasks: single-delete-vm.yaml
  when: pve_delete_vm is defined and pve_operation == "delete"

- name: Bulk rename template/vm
  ansible.builtin.include_tasks: bulk_rename_vm.yaml
  when: pve_bulk_rename_vms is defined
  with_items:
    - "{{ pve_bulk_rename_vms }}"

- name: Single rename template/vm
  ansible.builtin.include_tasks: single_rename_vm.yaml
  when: pve_current_vm_name is defined and pve_expected_vm_name is defined and pve_operation == "rename"
