---
- name: Get proxmox ticket
  ansible.builtin.uri:
    url: "{{ pve_cluster_url }}/api2/json/access/ticket"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ api_user }}"
      password: "{{ api_password }}"
    status_code: [200,500]
  register: pve_api_ticket