---
- name: Get proxmox ticket
  ansible.builtin.uri:
    url: "{{ pve_cluster_url }}/api2/json/access/ticket"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ pve_api_user }}"
      password: "{{ pve_api_password }}"
    status_code: 200
  register: pve_api_ticket
